val libpangocairo = PolyMLFFI.load_lib "";
use "PANGO_CAIRO_FC_FONT_MAP_CLASS.sml";
use "PANGO_CAIRO_FC_FONT_MAP.sml";
use "PANGO_CAIRO_FONT_CLASS.sml";
use "PANGO_CAIRO_FONT.sml";
use "PANGO_CAIRO_FONT_MAP_CLASS.sml";
use "PANGO_CAIRO_FONT_MAP.sml";
use "PANGO_CAIRO.sml";
use "polyml/PangoCairoFcFontMapClass.sml";
use "polyml/PangoCairoFontClass.sml";
use "polyml/PangoCairoFontMapClass.sml";
use "polyml/PangoCairoFcFontMap.sml";
use "polyml/PangoCairoFont.sml";
use "polyml/PangoCairoFontMap.sml";
use "polyml/PangoCairo.sml";
