val libvte = PolyMLFFI.load_lib "libvte-2.91.so.0";
val libgiraffevte = PolyMLFFI.load_lib "libgiraffe-vte-2.91.so";
use "VTE_CURSOR_BLINK_MODE.sml";
use "VTE_CURSOR_SHAPE.sml";
use "VTE_ERASE_BINDING.sml";
use "VTE_PTY_CLASS.sml";
use "VTE_PTY.sml";
use "VTE_PTY_ERROR.sml";
use "VTE_PTY_FLAGS.sml";
use "VTE_TERMINAL_CLASS.sml";
use "VTE_TERMINAL.sml";
use "VTE_WRITE_FLAGS.sml";
use "VTE.sml";
use "polyml/VteCursorBlinkMode.sml";
use "polyml/VteCursorShape.sml";
use "polyml/VteEraseBinding.sml";
use "polyml/VtePtyClass.sml";
use "polyml/VtePtyError.sml";
use "polyml/VtePtyFlags.sml";
use "polyml/VteTerminalClass.sml";
use "polyml/VteWriteFlags.sml";
use "polyml/VtePty.sml";
use "polyml/VteTerminal.sml";
use "polyml/Vte.sml";
