structure GtkSource : GTK_SOURCE =
  struct
    val completionErrorQuark_ = _import "gtk_source_completion_error_quark" : unit -> GUInt32.FFI.val_;
    val encodingGetCurrent_ = _import "gtk_source_encoding_get_current" : unit -> GtkSourceEncodingRecord.FFI.non_opt GtkSourceEncodingRecord.FFI.p;
    val encodingGetFromCharset_ = _import "mlton_gtk_source_encoding_get_from_charset" : Utf8.MLton.p1 * Utf8.FFI.non_opt Utf8.MLton.p2 -> GtkSourceEncodingRecord.FFI.opt GtkSourceEncodingRecord.FFI.p;
    val encodingGetUtf8_ = _import "gtk_source_encoding_get_utf8" : unit -> GtkSourceEncodingRecord.FFI.non_opt GtkSourceEncodingRecord.FFI.p;
    val fileLoaderErrorQuark_ = _import "gtk_source_file_loader_error_quark" : unit -> GUInt32.FFI.val_;
    val fileSaverErrorQuark_ = _import "gtk_source_file_saver_error_quark" : unit -> GUInt32.FFI.val_;
    val utilsEscapeSearchText_ = _import "mlton_gtk_source_utils_escape_search_text" : Utf8.MLton.p1 * Utf8.FFI.non_opt Utf8.MLton.p2 -> Utf8.FFI.non_opt Utf8.FFI.out_p;
    val utilsUnescapeSearchText_ = _import "mlton_gtk_source_utils_unescape_search_text" : Utf8.MLton.p1 * Utf8.FFI.non_opt Utf8.MLton.p2 -> Utf8.FFI.non_opt Utf8.FFI.out_p;
    structure BackgroundPatternType = GtkSourceBackgroundPatternType
    structure BracketMatchType = GtkSourceBracketMatchType
    structure BufferClass = GtkSourceBufferClass
    structure ChangeCaseType = GtkSourceChangeCaseType
    structure CompletionClass = GtkSourceCompletionClass
    structure CompletionActivation = GtkSourceCompletionActivation
    structure CompletionContextClass = GtkSourceCompletionContextClass
    structure CompletionError = GtkSourceCompletionError
    exception CompletionError = GtkSourceCompletionError
    structure CompletionInfoClass = GtkSourceCompletionInfoClass
    structure CompletionItemClass = GtkSourceCompletionItemClass
    structure CompletionProposalClass = GtkSourceCompletionProposalClass
    structure CompletionProviderClass = GtkSourceCompletionProviderClass
    structure CompletionWordsClass = GtkSourceCompletionWordsClass
    structure CompressionType = GtkSourceCompressionType
    structure DrawSpacesFlags = GtkSourceDrawSpacesFlags
    structure EncodingRecord = GtkSourceEncodingRecord
    structure FileClass = GtkSourceFileClass
    structure FileLoaderClass = GtkSourceFileLoaderClass
    structure FileLoaderError = GtkSourceFileLoaderError
    exception FileLoaderError = GtkSourceFileLoaderError
    structure FileSaverClass = GtkSourceFileSaverClass
    structure FileSaverError = GtkSourceFileSaverError
    exception FileSaverError = GtkSourceFileSaverError
    structure FileSaverFlags = GtkSourceFileSaverFlags
    structure GutterClass = GtkSourceGutterClass
    structure GutterRendererClass = GtkSourceGutterRendererClass
    structure GutterRendererAlignmentMode = GtkSourceGutterRendererAlignmentMode
    structure GutterRendererState = GtkSourceGutterRendererState
    structure LanguageClass = GtkSourceLanguageClass
    structure LanguageManagerClass = GtkSourceLanguageManagerClass
    structure MarkClass = GtkSourceMarkClass
    structure MarkAttributesClass = GtkSourceMarkAttributesClass
    structure NewlineType = GtkSourceNewlineType
    structure PrintCompositorClass = GtkSourcePrintCompositorClass
    structure RegionClass = GtkSourceRegionClass
    structure RegionIterRecord = GtkSourceRegionIterRecord
    structure SearchContextClass = GtkSourceSearchContextClass
    structure SearchSettingsClass = GtkSourceSearchSettingsClass
    structure SmartHomeEndType = GtkSourceSmartHomeEndType
    structure SortFlags = GtkSourceSortFlags
    structure StyleClass = GtkSourceStyleClass
    structure StyleSchemeClass = GtkSourceStyleSchemeClass
    structure StyleSchemeChooserClass = GtkSourceStyleSchemeChooserClass
    structure StyleSchemeChooserButtonClass = GtkSourceStyleSchemeChooserButtonClass
    structure StyleSchemeChooserWidgetClass = GtkSourceStyleSchemeChooserWidgetClass
    structure StyleSchemeManagerClass = GtkSourceStyleSchemeManagerClass
    structure TagClass = GtkSourceTagClass
    structure UndoManagerClass = GtkSourceUndoManagerClass
    structure ViewClass = GtkSourceViewClass
    structure ViewGutterPosition = GtkSourceViewGutterPosition
    structure Buffer = GtkSourceBuffer
    structure Completion = GtkSourceCompletion
    structure CompletionContext = GtkSourceCompletionContext
    structure CompletionInfo = GtkSourceCompletionInfo
    structure CompletionItem = GtkSourceCompletionItem
    structure CompletionProposal = GtkSourceCompletionProposal
    structure CompletionProvider = GtkSourceCompletionProvider
    structure CompletionWords = GtkSourceCompletionWords
    structure Encoding = GtkSourceEncoding
    structure File = GtkSourceFile
    structure FileLoader = GtkSourceFileLoader
    structure FileSaver = GtkSourceFileSaver
    structure Gutter = GtkSourceGutter
    structure GutterRenderer = GtkSourceGutterRenderer
    structure GutterRendererPixbufClass = GtkSourceGutterRendererPixbufClass
    structure GutterRendererTextClass = GtkSourceGutterRendererTextClass
    structure Language = GtkSourceLanguage
    structure LanguageManager = GtkSourceLanguageManager
    structure MapClass = GtkSourceMapClass
    structure Mark = GtkSourceMark
    structure MarkAttributes = GtkSourceMarkAttributes
    structure PrintCompositor = GtkSourcePrintCompositor
    structure Region = GtkSourceRegion
    structure RegionIter = GtkSourceRegionIter
    structure SearchContext = GtkSourceSearchContext
    structure SearchSettings = GtkSourceSearchSettings
    structure Style = GtkSourceStyle
    structure StyleScheme = GtkSourceStyleScheme
    structure StyleSchemeChooser = GtkSourceStyleSchemeChooser
    structure StyleSchemeChooserButton = GtkSourceStyleSchemeChooserButton
    structure StyleSchemeChooserWidget = GtkSourceStyleSchemeChooserWidget
    structure StyleSchemeManager = GtkSourceStyleSchemeManager
    structure Tag = GtkSourceTag
    structure UndoManager = GtkSourceUndoManager
    structure View = GtkSourceView
    structure GutterRendererPixbuf = GtkSourceGutterRendererPixbuf
    structure GutterRendererText = GtkSourceGutterRendererText
    structure Map = GtkSourceMap
    fun completionErrorQuark () = (I ---> GUInt32.FFI.fromVal) completionErrorQuark_ ()
    fun encodingGetCurrent () = (I ---> GtkSourceEncodingRecord.FFI.fromPtr false) encodingGetCurrent_ ()
    fun encodingGetFromCharset charset = (Utf8.FFI.withPtr ---> GtkSourceEncodingRecord.FFI.fromOptPtr false) encodingGetFromCharset_ charset
    fun encodingGetUtf8 () = (I ---> GtkSourceEncodingRecord.FFI.fromPtr false) encodingGetUtf8_ ()
    fun fileLoaderErrorQuark () = (I ---> GUInt32.FFI.fromVal) fileLoaderErrorQuark_ ()
    fun fileSaverErrorQuark () = (I ---> GUInt32.FFI.fromVal) fileSaverErrorQuark_ ()
    fun utilsEscapeSearchText text = (Utf8.FFI.withPtr ---> Utf8.FFI.fromPtr 1) utilsEscapeSearchText_ text
    fun utilsUnescapeSearchText text = (Utf8.FFI.withPtr ---> Utf8.FFI.fromPtr 1) utilsUnescapeSearchText_ text
  end
