#! /bin/bash

SUFFIX=gir

SML="sml-${SUFFIX}"

unset DIFF_EXISTS

for SOURCE in "${SML}"/*
do
  NAME=`basename ${SOURCE}`
  TARGET="../src/sml/${NAME}"

  if [ -e "${TARGET}" ]
  then
    if diff -rq "${TARGET}" "${SOURCE}" > /dev/null
    then
      printf "%-25s %-12s %-28s (not copied)\n" ${SOURCE} "same as" ${TARGET}
    else
      printf "%-25s %-12s %-28s (not copied)\n" ${SOURCE} "differs from" ${TARGET}
      DIFF_EXISTS=
    fi
  else
    if cp -an "${SOURCE}" "${TARGET}"
    then
      printf "%-25s %-12s %-28s\n" ${SOURCE} "copied from" ${TARGET}
    else
      echo "error: failed to copy ${SOURCE} to ${TARGET}"
    fi
  fi
done

if [ -v DIFF_EXISTS ]
then
  echo
  echo "Differences exist, review and remove existing directories."
  echo "Starting 'meld ${SML} ../src/sml'..."
  meld "${SML}" ../src/sml
fi
