signature G_LIB_UNICODE_TYPE =
  sig
    datatype enum =
      CONTROL
    | FORMAT
    | UNASSIGNED
    | PRIVATE_USE
    | SURROGATE
    | LOWERCASE_LETTER
    | MODIFIER_LETTER
    | OTHER_LETTER
    | TITLECASE_LETTER
    | UPPERCASE_LETTER
    | SPACING_MARK
    | ENCLOSING_MARK
    | NON_SPACING_MARK
    | DECIMAL_NUMBER
    | LETTER_NUMBER
    | OTHER_NUMBER
    | CONNECT_PUNCTUATION
    | DASH_PUNCTUATION
    | CLOSE_PUNCTUATION
    | FINAL_PUNCTUATION
    | INITIAL_PUNCTUATION
    | OTHER_PUNCTUATION
    | OPEN_PUNCTUATION
    | CURRENCY_SYMBOL
    | MODIFIER_SYMBOL
    | MATH_SYMBOL
    | OTHER_SYMBOL
    | LINE_SEPARATOR
    | PARAGRAPH_SEPARATOR
    | SPACE_SEPARATOR
    include
      ENUM
        where type t = enum
  end
